# -*- restclient -*-
# Get blockchain
GET http://localhost:8000/chain
Content-Type: application/json

# Create transaction
POST http://localhost:8000/transaction
content-type: application/json

{
  "sender": "siobhan",
  "recipient": "jeff",
  "amount": 0.25
}

# Mine block
POST http://localhost:8000/mine
content-type: application/json
